config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :searches, only: [:new, :create] do
    resources :articles, only: [:index, :show]
  end

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :search
  belongs_to :provider, optional: true
  has_many :images, dependent: :destroy
  has_many :stocks, dependent: :destroy

  def self.prix
    ["-","croissant", "decroissant"] # '-' = pas de tri sur le prix
  end
end

app/controllers/articles_controller.rb
require 'json'
require 'open-uri'

class ArticlesController < ApplicationController
  before_action :set_search_and_near_stores, only: [:index, :show]

  include ActionView::Helpers::NumberHelper

  def index
    # listons les providers qui se trouvent dans le rayon de recherche
    near_stores_providers = []
    @near_stores.each do |store|
      near_stores_providers << store.provider if !near_stores_providers.include?(store.provider)
    end
    # prendre les articles qui ont du stock et dont le fournisseur a un store à proximité
    @articles = @search.articles.select { |a| a.stocks.map { |s| s.available}.include?(true) && near_stores_providers.include?(a.provider)}
    return false if @articles == nil

    stores = []

    #find stores from enseigne with articles with stock
    @articles.each do |article|
      article.provider.stores.each do |store|
        stores << store[:id]
      end
    end
    compute_stores_and_markers(@search, stores, nil)
    @providers = Provider.all
    @provider = params[:provider]
  end

  def show
    @article = Article.find(params[:id])
    stores = []
    @article.provider.stores.each do |store|
      stores << store[:id]
    end
    compute_stores_and_markers(@search, stores, @article)
    @select_prix = params[:select_prix]
  end


  private

  def set_search_and_near_stores
    @search = Search.find(params[:search_id])
    @near_stores = []
    near_stores = Store.near(@search.input_address, @search.distance, units: :km)
                       .where.not(latitude: nil, longitude: nil)
    near_stores.each do |store|
      @near_stores << store
    end
  end

  def sort_markers_stores
    hash_distances = {}
    @markers_stores.each_with_index do |store, index|
      distance = Geocoder::Calculations.distance_between([store.latitude,store.longitude],[@search.latitude,@search.longitude])
      hash_distance = {}
      hash_distance[:store] = store
      hash_distance[:distance] = distance
      hash_distances[index.to_s] = hash_distance
    end
    sort_results = hash_distances.sort_by { |k, v| v[:distance] }
    @markers_stores = []
    @markers_distances = []
    sort_results.each do |sort_result|
      @markers_stores << sort_result[1][:store]
      @markers_distances << sort_result[1][:distance]
    end
  end

  def distance_and_travel_times(store)
    travel_modes = ['driving', 'walking', 'bicycling', 'transit']
    travel_datas = {}
    error_message = 'sorry, api limited!'
    travel_modes.each do |mode|
      distance = error_message
      travel_time = error_message
      do_request_for_test = false #pour forcer la requête, comme si on est en prod, !!!! à mettre à false en prod
      if Rails.env != 'development' || do_request_for_test
        url = "https://maps.googleapis.com/maps/api/distancematrix/json?units=km&origins=#{@search.latitude},#{@search.longitude}&destinations=#{store.latitude},#{store.longitude}&mode=#{mode}&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
        response_serialized = open(url).read
        response = JSON.parse(response_serialized)
        unless response['error_message']
          distance = response["rows"][0]["elements"][0]["distance"]["text"] if response["rows"][0]["elements"][0]["distance"]
          travel_time = response["rows"][0]["elements"][0]["duration"]["text"] if response["rows"][0]["elements"][0]["duration"]
        end
      end
      travel_mode_response = {}
      travel_mode_response['distance'] = distance
      travel_mode_response['time'] = travel_time
      travel_datas[mode] = travel_mode_response
    end
    return travel_datas
  end

  def compute_stores_and_markers(search, stores, article)
    stock_stores = []
    @stores = Store.find(stores.sort.uniq)
    stock_stores = @stores && @near_stores
    unless article.nil?
      stock_stores = stock_stores.select {|s| s.provider == article.provider}
    end

    @markers = []
    @markers_stores = [] #les stores qui auront un marker sur la map
    # Fill Gmaps with stores having stock
    # @markers = @stores.map { |store| {lat: store.latitude, lng: store.longitude} }
    stock_stores.each do |store|
      next if store.provider == nil
      next if store.provider.articles == nil
      @markers_stores << store
    end

    # faisons un tri des @markers_stores, de manière à les lister du plus proche au plus éloigné

    sort_markers_stores

    @markers_stores.each_with_index do |store, index|
      @start = []
      @start << { lat: @search.latitude, lng: @search.longitude }

      distance = 0 #@markers_distances[index]

      travel_datas = {}
      travel_datas = distance_and_travel_times(store) unless article.nil? #inutile de calculer pour la page index, on ne le fait que pour le show (1 article)

      @markers << {lat: store.latitude,
                   lng: store.longitude,
                   distance: distance,          # distance provenant du geocoder de ruby (à vol d'oiseau ) (!!! ne pas utiliser dans le js !!!)
                   traveldatas: travel_datas,   # informations qui viennent de l'api de google et qui donnent les détails pour chaque mode de transport
                   phone: store.phone,
                   address: store.address,
                   title: store.name,
                   enseigne: store.provider.name,
                   logo: store.provider.logo,
                   schedules: store.schedules,
                   posinlist: index,
                   # icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
                   # icon: 'https://findicons.com/files/icons/951/google_maps/32/clothes.png' # https://findicons.com/pack/951/google_maps/7
                   # icon: 'https://findicons.com/files/icons/2771/batch/64/store.png' # https://findicons.com/pack/951/google_maps/7
                   # icon: 'https://findicons.com/files/icons/2482/icons8_ever_growing_set_of_windows_8_metro_style_icons/26/shop.png' # https://findicons.com/pack/951/google_maps/7
                   icon: 'https://findicons.com/files/icons/2342/pixelophilia2/32/shop.png' # https://findicons.com/pack/951/google_maps/7
                  }
    end

  end

  def params_article
    params.require(:article).permit(:title, :sku, :description, :price, :selected)
  end
end

app/views/articles/_searchnavbar.html.erb
<div class="wrapper navbar-search">
  <div class="container">
    <div class="row center-block">
      <div class="col-xs-12 col-sm-3">
        <div class="navbar-search-left center-img">
          <%= link_to root_path do %>
          <%= image_tag "http://res.cloudinary.com/dwoel6eny/image/upload/v1528979620/finaly_2.png", height:114, width: 150  %>
        <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-9 inline">
        <%= simple_form_for "", url: searches_path, html: {class: "form-inline", novalidate: false} do |f| %>
            <div class="form-group">
            <%= f.input :keywords, :label =>"", :placeholder =>"Which cloth?", required: true, input_html: {value: @search.keywords } %>
          </div>
            <div class="form-group">
            <div id="autocomplete">
            <%= f.input :input_address, :label =>"", :placeholder =>"Where ?", required: true, input_html: {value: @search.input_address } %>
            </div>
          </div>
          <div class="form-group">
            <%= f.input :distance, collection: Search.distances, :label =>"", label_method: :label, value_method: :value, selected: @search.distance %>
          </div>
          <div class="form-group center">
            <button class="icon"><i class=" btn fa fa-search"> Search</i></button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<title>QuickFind Search</title>
  <%= render 'searchnavbar' %>
  <div class="container">
    <div class="row">
      <div class ="filtre" >
        <div class="col-xs-12 col-sm-3 col-md-4">
          <label for="select_prix">prix:</label>
          <select id="select_prix">
            <% Article.prix.each_with_index do |sort, index| %>
              <option value=<%= sort %>><%= sort %></option>
            <% end %>
          </select>
        </div>
        <div class="col-xs-12 col-sm-3 col-md-4">
          <!-- pour le tri/provider, listons seulement les providers qui ont actuellement un article dans la liste des articles -->
          <!-- mettons par defaut la valeur de non tri -->
          <% current_enseignes = ["-"] %>
          <% @articles.each { |a| current_enseignes << a.provider.name if !current_enseignes.include?(a.provider.name) } %>
          <label for="select_enseigne">enseignes:</label>
          <select id="select_enseigne">
            <% current_enseignes.each_with_index do |sort, index| %>
              <option value=<%= sort %>><%= sort %></option>
            <% end %>
          </select>
        </div>
      </div>
    </div>
    <div class="row block-cards">
      <div class="col-xs-12 col-sm-8">
        <div class="row cards-panel">
          <% @articles.each do |article| %>
            <div class="col-xs-12 col-sm-6 col-md-4 col-card">
              <div class="card" style="background-image: url(<%= article.images.first.url %>);">
                  <%= image_tag(article.provider.logo, class: "card-user") %>
                  <a class="card-link" href="#" ></a>
                <%= link_to "", search_article_path(article.search, article), class: "card-link" %>
              </div>
              <div class="description">
                <p style="display: none;" class="provider"><%= article.provider.name %></p>
                <p class="title"><%= article.title %></p>
                <p class="prix"><span class="numeric-prix"><%= number_to_currency((article.price.to_f / 100), locale: :fr, precision: 2, strip_insignificant_zeros: true) %></span></p>
                <p><%= @markers_stores.select{|s| s.provider == article.provider}.count %> magasin(s) près de chez vous</p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div id="map" data-markers="<%= @markers.to_json %>" data-stores="<%= @markers_stores.to_json %>" data-distances="<%= @distances.to_json %>" data-start="<%= @start.to_json %>"></div>
      </div>
    </div>
  </div>
</div>
<a href="#" class="scrollToTop">Back to top</a>
<%= render 'pages/footer' %>

app/views/articles/show.html.erb
<title>QuickFind Article</title>
<%= render 'searchnavbar' %>

<div class="wrapper">
  <div class="container">
    <div id="backlist">
      <a href="javascript:history.back()"><p class="glyphicon glyphicon-arrow-left" aria-hidden="true"><span class="button-back"> Back to list</span></p></a>
    </div>
    <div class="row">
    </div>
    <div class="row showrow">
      <div class="col-xs-12 col-md-6">
        <%= image_tag @article.images.first.url, class: "img-responsive center-img", width: "500" %>
      </div>
      <div class="col-xs-12 col-md-6 card-details">
        <div class="article-description">
          <h2><%= @article.title %></h2>
          <p><%= @article.description %></p>
          <div class="price">
            <p><%= number_to_currency((@article.price.to_f / 100), locale: :fr, precision: 2, strip_insignificant_zeros: true) %> </p>
          </div>
          <div class="form-group select-size">
            <h4><label for="selsize">Available sizes : </label>
            <select class="selectpicker" id="selsize" data-width="auto">
              <%=  @article.stocks.each do |stock| %>
                <% if stock.available == true %>
                  <option value=stock.size><%= stock.size %></option>
                <% else %>
                  <option value=stock.size disabled><%= stock.size %></option>
                <% end %>
              <% end %>
            </select></h4>
          </div>
          <div>
<!--           <a href=<%= @article.url %> title="" target="_blank" class: "btn btn-primary" width: 100 %></a> -->
            <h4><a href="<%= @article.url %>" target="_blank" role="button">Book Online</a></h4>
          </div>
          <div id="vendor">
            <h4><a href="<%= @article.url %>" target="_blank"><%= image_tag @article.provider.logo, class: "img-responsive center-block", width: "150" %></a></h4>
          </div>
        </div>
      </div>
     </div>
   </div>
   <div class="container">
     <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="mapshow" id="map" data-markers="<%= @markers.to_json %>" data-stores="<%= @markers_stores.to_json %>" data-distances="<%= @distances.to_json %>" data-start="<%= @start.to_json %>"></div>
      </div>
      <div class="col-xs-12 col-md-6 card-details">
        <div class="outline">
          <div id="travel-mode">
            <h4>Travel Mode:
            <select id="mode-travel">
              <option value="driving">Driving</option>
              <option value="walking">Walking</option>
              <option value="bicycling">Bicycling</option>
              <option value="transit">Transit</option>
            </select> </h4>
          </div>
          <div class="travel">
            <div>
              <h4><i class="fas fa-stopwatch"></i><h4>
              <h4><span id="time-travel">my time travel</span></h4>
            </div>
            <div>
              <h4><i class="fas fa-shipping-fast"></i></h4>
              <h4><span id="store-distance"></span></h4>
            </div>
          </div>
          <div>
            <h4>Today :
              <span><i class="fas fa-clock"></i></span>
              <span id="open-hours-today"></span>
            </h4>
          </div>
          <div id="webstore">
            <a id="navigation" class="btn btn-success" target="_blank" href="#" role="button">Go to store !&nbsp; <%= image_tag 'http://images.frandroid.com/wp-content/uploads/2017/06/logo-google-maps-2017.png', width: "40" %></a>
          </div>
        </div>
        <div class="informations">
         <div class="separator">
           <h4 id="store-address"><%= @markers_stores.first.address %></h4>
           <h4><i class="fas fa-phone">&nbsp;</i><span id="store-phone"></span></h4>
         </div>
         <div class="open-hours">
           <p>Open Hours :</p>
           <div id="line"></div>
           <div class="separator">
             <p id="store-schedules"></p>
           </div>
           <div id="line"></div>
         </div>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'pages/footer' %>